// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:bcdec5ad-c7f1-450a-8110-541d0c7809a4",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_ps21mMr9T",
    "aws_user_pools_web_client_id": "3dhonc593bjhejrddkd1ap71gj"
};


export default awsmobile;
